apiVersion: apps/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: elkibana
  name: elkibana
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: elkibana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: elkibana
    spec:
      containers:
      - image: nshou/elasticsearch-kibana:latest
        imagePullPolicy: Always
        name: elkibana
        ports:
        - containerPort: 81
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
