apiVersion: v1
kind: Service
metadata:
  name: elkibana
  labels:
    run: elkibana
spec:
  selector:
    run: elkibana
  ports:
  - name: http
    protocol: TCP
    port: 5602
    targetPort: 5601
  type: ClusterIP
